POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNWU5YWYyNDIzYzgzODBhODJjODAzODYyIiwiaWF0IjoxNTg3MjQwNDMyfQ.l92rx6-6QClo-ZdhXa1YNUeD3g2odi_07exZD5lTz3c

{
  "title": "FP vs. OO",
  "author": "Robert C. Martin",
  "url": "https://blog.cleancoder.com/uncle-bob/2018/04/13/FPvsOO.html",
  "likes": "0"
}


### wrong token
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer djfksjfslfjslfdjskljfsl

{
  "title": "FP vs. OO",
  "author": "Robert C. Martin",
  "url": "https://blog.cleancoder.com/uncle-bob/2018/04/13/FPvsOO.html",
  "likes": "0"
}

### no token
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "FP vs. OO",
  "author": "Robert C. Martin",
  "url": "https://blog.cleancoder.com/uncle-bob/2018/04/13/FPvsOO.html",
  "likes": "0"
}

### misisng infos token
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNWU5YWYyNDIzYzgzODBhODJjODAzODYyIiwiaWF0IjoxNTg3MjQwNDMyfQ.l92rx6-6QClo-ZdhXa1YNUeD3g2odi_07exZD5lTz3c

{
  "title": "FP vs. OO",
  "author": "Robert C. Martin",
  "likes": "0"
}


###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNWU5YWYyNDIzYzgzODBhODJjODAzODYyIiwiaWF0IjoxNTg3MjQwNDMyfQ.l92rx6-6QClo-ZdhXa1YNUeD3g2odi_07exZD5lTz3c

{
  "title": ",kljljk",
  "author": "jlkk",
  "url": "hjkh",
  "likes": "0"
}
